services:

  backend:
    build: .
    image: library-backend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000

      DB_USER: postgres
      DB_HOST: db
      DB_NAME: lms_db
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}

      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      REDIS_URL: redis://redis:6379

      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:16
    container_name: library_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: lms_db

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lms_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: library-redis
    ports:
    - "6379:6379"
volumes:
  postgres_data: